### ISSUE TITLE
Add support for the new 2018+ json implementation

### ISSUE THREAD

**Issue by Yakov5776** [BrentDaMage/PHP-RCCServiceSoap#1]

**Comment by BrentDaMage** [comment]
u

**Comment by Yakov5776** [comment]
are

**Comment by ghost** [comment]
an

**Comment by powderedd** [comment]
idiot

**Comment by selective5296** [comment]
suck an egg

**Comment by powderedd** [comment]
or eat one too

**Comment by BrentDaMage** [comment]
This is a SOAP framework. Support for a JSON implementation will not be added. This would be something that would be done via a separate framework. Perhaps some scaffolding can be separated out from this project and be used as some sort of Roblox.Grid library. Then we could do two separate SOAP and JSON frameworks.
