### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by JustGoodGame** [BrentDaMage/PHP-RCCServiceSoap#2]
Most of the commands crash RCCService

**Comment by BrentDaMage** [comment]
Which version of RCCService are you using?

**Comment by ghost** [comment]
> Which version of RCCService are you using?

2017

**Comment by BrentDaMage** [comment]
It should still work on 2017. It's most likely an issue with RCCService not being patched propertly.

**Comment by ghost** [comment]
how i can patch rccservice?

**Comment by JustGoodGame** [comment]
> Which version of RCCService are you using?

0.285.0.49012

**Comment by PaPaTrolls** [comment]
> how i can patch rccservice?

as obviously it is you're probably some v3rm user, and don't know what this is, suggest you leaving this repo.

**Comment by BrentDaMage** [comment]
Any luck with resolving your crash issue?

**Comment by BrentDaMage** [comment]
No response from OP. Seemed like a bad-patch issue.

**Comment by JustGoodGame** [comment]
Hi, sorry for the long reply, I'm not much active on GitHub. I ended up using the WSDL and implemented it myself.
