### ISSUE TITLE
how to setup?

### ISSUE THREAD

**Issue by ghost** [BrentDaMage/PHP-RCCServiceSoap#3]
uh
im really new at php
http://localhost:64989/ just shows a xml file with "HTTP Get method is not implemented"

**Comment by BrentDaMage** [comment]
The basic usage example can be found here: https://github.com/BrentDaMage/PHP-RCCServiceSoap/blob/main/README.md
If you have any specific questions, please feel free to ask. For now I'm closing the issue.

**Comment by brannanz** [comment]
How do we set up the actual RCCService server itself
