### ISSUE TITLE
why does openjob crash rccservice?

### ISSUE THREAD

**Issue by powderedd** [BrentDaMage/PHP-RCCServiceSoap#6]
Code:
```
<?php
function load_model($class_name)
{
	$path_to_file = 'Assemblies/Roblox/Grid/Rcc/' . $class_name . '.php';

	if (file_exists($path_to_file)) {
		require $path_to_file;
	}
}

load_model('RCCServiceSoap');
load_model('Job');
load_model('LuaValue');
load_model('LuaType');
load_model('ScriptExecution');
load_model('Status');

$rccsoapclient = new Roblox\Grid\Rcc\RCCServiceSoap();
$a = new Roblox\Grid\Rcc\Job(1);
echo($rccsoapclient->OpenJob(1, "print('Hello World!')"));

?>
```

**Comment by thexkey** [comment]
i have tried this, it also crashes if you even try to give it any commands (such as GetVersion) so its not a OpenJob related issue

**Comment by powderedd** [comment]
getversion works for me

**Comment by thexkey** [comment]
yeah it turns out i forgot to comment out the job on your sample code when i changed it to getversion

**Comment by thexkey** [comment]
I forgot to tell you when I asked brent about this since I had the same problem, he says you were doing jobs wrong. (It is not numbers, it's a string)

Also now there is proper example code in the repo now.

**Comment by powderedd** [comment]
oh, why wouldnt it handle numbers?
i probably also didn't make a scriptexecution class

**Comment by powderedd** [comment]
and i tried the sample code but with numbers, and it works.

**Comment by powderedd** [comment]
oh well, it works now

**Comment by thexkey** [comment]
i dont know then , numbers for me crash 100% of the time, it HAS to be a string for me

**Comment by BrentDaMage** [comment]
It's possible that the numbers are being automatically converted to strings, but as far as RCCService goes, the job IDs are UUIDs, not integers.

**Comment by thexkey** [comment]
perhaps, but unlikely as i do not see any conversion when looking thru the API's source to string.

**Comment by BrentDaMage** [comment]
> perhaps, but unlikely as i do not see any conversion when looking thru the API's source to string.

I was more referring to PHP doing it automatically.

**Comment by thexkey** [comment]
i see. i'm not aware of any such feature other than arrays being able to be turned into a string improperly (although that's not recommended and will throw a warning)

**Comment by powderedd** [comment]
a bit late, but it might be differences of PHP versions you might both be using
